import type { Person } from './wp';

export const mockPeople: Person[] = [
  {
    id: 1,
    slug: 'ludwig-wittgenstein',
    name: 'Dr. Ludwig Wittgenstein',
    titulo: 'Profesor titular de Filosofía del Lenguaje',
    departamento: 'Filosofía',
    areasInvestigacion: ['Filosofía del lenguaje', 'Lógica', 'Filosofía de la mente'],
    email: 'l.wittgenstein@humanidades.edu.mx',
    bio: '<p>Autor de dos de las obras más influyentes de la filosofía occidental: el <em>Tractatus Logico-Philosophicus</em> y las <em>Investigaciones filosóficas</em>. Su pensamiento atraviesa la pregunta por los límites del lenguaje y las formas de vida que lo constituyen.</p>',
    photoUrl: undefined,
    publicaciones: [
      {
        titulo: 'Investigaciones filosóficas',
        autores: 'Wittgenstein, L.',
        anio: 1953,
        url: undefined,
      },
      {
        titulo: 'Tractatus Logico-Philosophicus',
        autores: 'Wittgenstein, L.',
        anio: 1921,
        url: undefined,
      },
    ],
  },
  {
    id: 2,
    slug: 'judith-butler',
    name: 'Dra. Judith Butler',
    titulo: 'Investigadora titular de Teoría Crítica',
    departamento: 'Filosofía',
    areasInvestigacion: ['Teoría de género', 'Filosofía política', 'Ética', 'Estudios culturales'],
    email: 'j.butler@humanidades.edu.mx',
    bio: '<p>Figura central de la teoría continental contemporánea. Su obra <em>El género en disputa</em> reformuló los estudios de género al introducir la noción de performatividad. Trabaja en la intersección entre ética, vulnerabilidad y vida política.</p>',
    photoUrl: undefined,
    publicaciones: [
      {
        titulo: 'El género en disputa',
        autores: 'Butler, J.',
        anio: 1990,
        url: undefined,
      },
      {
        titulo: 'Cuerpos que importan',
        autores: 'Butler, J.',
        anio: 1993,
        url: undefined,
      },
      {
        titulo: 'Vida precaria',
        autores: 'Butler, J.',
        anio: 2004,
        url: undefined,
      },
    ],
  },
  {
    id: 3,
    slug: 'georg-hegel',
    name: 'Dr. Georg Wilhelm Friedrich Hegel',
    titulo: 'Profesor emérito de Idealismo y Dialéctica',
    departamento: 'Filosofía',
    areasInvestigacion: ['Idealismo alemán', 'Dialéctica', 'Filosofía del espíritu', 'Filosofía de la historia'],
    email: 'g.hegel@humanidades.edu.mx',
    bio: '<p>Arquitecto del sistema idealista más ambicioso de la modernidad. La <em>Fenomenología del espíritu</em> traza el recorrido de la conciencia hacia el saber absoluto. Su lógica dialéctica influyó decisivamente en Marx, Sartre y la tradición continental.</p>',
    photoUrl: undefined,
    publicaciones: [
      {
        titulo: 'Fenomenología del espíritu',
        autores: 'Hegel, G.W.F.',
        anio: 1807,
        url: undefined,
      },
      {
        titulo: 'Ciencia de la lógica',
        autores: 'Hegel, G.W.F.',
        anio: 1816,
        url: undefined,
      },
    ],
  },
  {
    id: 4,
    slug: 'hannah-arendt',
    name: 'Dra. Hannah Arendt',
    titulo: 'Investigadora titular de Filosofía Política',
    departamento: 'Filosofía',
    areasInvestigacion: ['Filosofía política', 'Teoría del totalitarismo', 'Acción y libertad', 'Pensamiento y juicio'],
    email: 'h.arendt@humanidades.edu.mx',
    bio: '<p>Pensadora central del siglo XX cuyo análisis del totalitarismo y la condición humana siguen siendo referencias ineludibles. Su distinción entre labor, trabajo y acción reformuló los fundamentos de la filosofía política moderna.</p>',
    photoUrl: undefined,
    publicaciones: [
      {
        titulo: 'Los orígenes del totalitarismo',
        autores: 'Arendt, H.',
        anio: 1951,
        url: undefined,
      },
      {
        titulo: 'La condición humana',
        autores: 'Arendt, H.',
        anio: 1958,
        url: undefined,
      },
    ],
  },
  {
    id: 5,
    slug: 'bertrand-russell',
    name: 'Dr. Bertrand Russell',
    titulo: 'Profesor titular de Lógica y Filosofía Analítica',
    departamento: 'Filosofía',
    areasInvestigacion: ['Lógica matemática', 'Epistemología', 'Filosofía analítica', 'Teoría del conocimiento'],
    email: 'b.russell@humanidades.edu.mx',
    bio: '<p>Cofundador de la filosofía analítica y uno de los lógicos más importantes de la historia. Sus <em>Principia Mathematica</em>, escritos junto a Whitehead, intentaron fundamentar las matemáticas en la lógica pura. Premio Nobel de Literatura en 1950.</p>',
    photoUrl: undefined,
    publicaciones: [
      {
        titulo: 'Principia Mathematica',
        autores: 'Russell, B. & Whitehead, A.N.',
        anio: 1910,
        url: undefined,
      },
      {
        titulo: 'Los problemas de la filosofía',
        autores: 'Russell, B.',
        anio: 1912,
        url: undefined,
      },
    ],
  },
];
